version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: aryanrarh/zaapier-frontend:latest
    ports:
      - "80:3000"
    env_file:
      - frontend.env
    depends_on:
      primary-backend:
        condition: service_started

  primary-backend:
    image: aryanrarh/zaapier-primary-backend:latest
    ports:
      - "4000:4000"
    env_file:
      - primary-backend.env
    depends_on:
      kafka:
        condition: service_healthy

  hooks:
    image: aryanrarh/zaapier-hooks:latest
    ports:
      - "3002:3002"
    env_file:
      - hooks.env
    depends_on:
      kafka:
        condition: service_healthy

  processor:
    image: aryanrarh/zaapier-processor:latest
    ports:
      - "3000:3000"
    env_file:
      - processor.env
    depends_on:
      kafka:
        condition: service_healthy

  worker:
    image: aryanrarh/zaapier-worker:latest
    env_file:
      - worker.env
    depends_on:
      kafka:
        condition: service_healthy

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped 